In [1]:
import numpy as np

In [15]:
print(np.random.randint(-5,10,size=[3,3]))

[[ 4  2  1]
 [-3  0  6]
 [ 1  4  7]]


In [8]:
print(np.random.random())

0.6072482944878606


In [18]:
# Pick 10 items from a given list
print(np.random.choice(['a', 'e' , 'i' , 'o' , 'u'], size=10))
print(np.random.choice([1,2,3], size=5))

['a' 'u' 'i' 'e' 'o' 'a' 'a' 'i' 'a' 'o']
[3 3 3 1 3]


In [8]:
print(np.random.choice(['a', 'e' , 'i' , 'o' , 'u'], size=(4,4)))

[['e' 'u' 'e' 'u']
 ['e' 'u' 'a' 'e']
 ['a' 'u' 'a' 'i']
 ['a' 'u' 'a' 'i']]


In [9]:
# Pick 10 items from a given list with a predefined probability 'p' --- percentage of each item
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, 0.1, 0.1, 0.4,0.1]))

['a' 'o' 'u' 'a' 'o' 'u' 'u' 'e' 'o' 'a']


In [10]:
"".join(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, 0.1, 0.1, 0.4,0.1]))

'ieuaeeaaoa'

In [20]:
na=np.array([111,222,23,445,656,33,88,69,1232,5,66])
print(np.min(na))
print(np.max(na))
print(np.mean(na))
print(np.std(na))
print(np.median(na)) 

5
1232
268.1818181818182
361.2047563821078
88.0


In [12]:
a=np.array([1,1,1,1,1,1,1,1,1,1])
print(a.std())    # standard deviation

0.0


In [13]:
%pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [1]:

# Matrix

import scipy.linalg as slin
import numpy as np

a = np.array([[ 3, -5, 8],
              [-1, 2, 3],
              [-5, -6, 2]])

print(slin.det(a))

259.0


In [4]:
import numpy as np

a = np.array([[ 3, -5, 8],
              [-1,  2, 3],
              [-5, -6, 2]])


print(np.trace(a))    # sum of the diagnol elements

print(slin.inv(a))    # inverse


7
[[ 0.08494208 -0.14671815 -0.11969112]
 [-0.05019305  0.17760618 -0.06563707]
 [ 0.06177606  0.16602317  0.003861  ]]


In [13]:
# Transpose of a matrix 
a = [[ 3, -5, 8],
     [-1, 2, 3],
     [-5, -6, 2]]

print(np.transpose(a))


[[ 3 -1 -5]
 [-5  2 -6]
 [ 8  3  2]]


In [ ]:
# Matrix Multiplication

import numpy as np

a=np.matrix([[ 3, -5, 8],
             [-1, 2, 3],
             [-5, -6, 2]])

b=np.matrix([[ 3],
             [ 4],
             [-1]])

print(a*b)


[[-19]
 [  2]
 [-41]]


In [ ]:
# Solving linear problem
# x+2y+3z=10
# 2x+3y+4z=15
# 3x+y+5z=20


a=[[1,2,3],   
   [2,3,4],
   [3,1,5]]

b=[10,15,20]
print(slin.det(a))

x=slin.solve(a,b)
print(x)

-6.0
[2.50000000e+00 1.26882631e-16 2.50000000e+00]


In [19]:
print(np.random.randint(-5,9))

7


In [21]:
print(np.random.choice([1,2,55,6,8],size=(3,4)))

[[ 2  1  8  2]
 [ 1  1  8 55]
 [55  6  6  6]]


In [22]:
import string as st

import random 

In [32]:
print(["".join(random.choice(st.ascii_letters+st.digits+st.punctuation) for i in range(8))])

['VE8x34v<']


In [33]:
# Import Numpy Library
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from IPython.display import Image

In [34]:
arr1=np.array([1,2,3,4,5,])
arr1

array([1, 2, 3, 4, 5])

In [36]:
print(arr1.dtype)

int64


In [ ]:
# Convert interger array into float
arr2=arr1.astype(float)

print(arr2)

[1. 2. 3. 4. 5.]


In [46]:
print(arr1.dtype)
print(arr2.dtype)

int64
float64


In [22]:
# Generate numbers between 0 to 100 with a space of 10
print(np.arange(0,100,10))

[ 0 10 20 30 40 50 60 70 80 90]
