In [2]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
print(np.__version__)

2.2.5


In [12]:
x=[1,2,3,4,5,6,7,8,9]
na= np.array(x)
print(na)

[1 2 3 4 5 6 7 8 9]


In [7]:
# Operations

print(na-5)
print(na+5)
print(na*5)
print(na/5)
print(na%5)

[-4 -3 -2 -1  0  1  2  3  4]
[ 6  7  8  9 10 11 12 13 14]
[ 5 10 15 20 25 30 35 40 45]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[1 2 3 4 0 1 2 3 4]


In [6]:
# shape--1D

x=[1,2,3,4,5,6,7,8,9]
na=np.array(x)
print(na.shape)  # Output: (9,)

(9,)


In [ ]:
# 2D
x=[[1,2,3],
   [4,5,6],
   [7,8,9]]
na=np.array(x)
print(na.shape)


(3, 3)


In [ ]:
x=[[1],[2],[3],[4],[5],[6],[7],[8]]
na=np.array(x)
print(na.shape)
print(na.dtype) # int64


(9, 1)
int64


In [33]:
x=[[[1,2,3,4,5,6,7,8,9]]]
na=np.array(x)
print(na.shape)


(1, 1, 9)


In [8]:
# reshape
x=[[1,2,3],  # (2,3)
   [4,5,6]]
na=np.array(x)
print(na.reshape(3,2),"\n")
print(na.reshape(1,6),"\n")
print(na.reshape(6,1),"\n")

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 3 4 5 6]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 



In [ ]:
x=[[1,2,3],  # (2,3)
   [4,5,6]]
na=np.array(x)
print(na.flatten()) # Brings all the datas into single dimension (flat)

[1 2 3 4 5 6]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=a+b  # It adds the corresponding elements, doesnot concate here
print(c)

[ 6  8 10 12]


In [ ]:
# For concate
# Horizontally
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
# For concate
# Vertically
a=[1,2,3]
b=[4,5,6]
c=[7,8,9]
np.vstack((a,b,c))
# Horizontally




array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])